apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: mycontainer
        image: npsoni/webapp
        ports:
        - containerPort: 80
