apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: mycontainer
        image: httpd
        ports:
        - containerPort: 80
