apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordprress
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: wordpress
    tier: backend
